language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
notifications:
  email: false
cache:
  directories:
    - node_modules
# allow headful tests
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
jobs:
  include:
    - node_js: "8.11.3"
script:
  - npm run test
deploy:
  provider: script
  skip_cleanup: true
  script: npm run build:chrome; npm run deploy:chrome; npm run build:firefox; npm run deploy:firefox
  on:
      branch: master
      # the deployment will be skipped if the last commit doesn't touch the manifest.json file
      condition: $(git diff-tree --no-commit-id --name-only -r HEAD | sed -n '/manifest/ q 1'; echo $?) = 1